name: cap
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - ipykernel
  - ipython
  - jupyterlab
  - pytorch::pytorch=2.4.0
  - pytorch::pytorch-cuda=12.4
  - pytorch::torchvision=0.19.0
  - pytorch::torchaudio=2.4.0
  - torchmetrics
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - pillow
  - tqdm
  - timm
  - torchinfo
  - tensorboard
  - librosa
  - spacy
  - einops
  - requests
  - pip